### ISSUE TITLE
ModuleInspector fails

### ISSUE THREAD

**Issue by arnoblalam** [SublimeHaskell/SublimeHaskell#152]
When I open up SublimeText, I see an x next to the "Loading Standard Modules for Cabal".

I get the following errors on the console (by pressing Ctrl + `). (I can build the project from command line using "cabal build").

```
Sublime Haskell: loading standard modules info for cabal failed with Can't convert 'list' object to str implicitly
Exception in thread Thread-2:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "/Users/arnoblalam/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 915, in run
    '-outputdir', CABAL_INSPECTOR_OBJ_DIR])
  File "/Users/arnoblalam/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 135, in call_and_wait
    return call_and_wait_with_input(command, None, **popen_kwargs)
  File "/Users/arnoblalam/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 165, in call_and_wait_with_input
    extended_env = get_extended_env()
  File "/Users/arnoblalam/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 131, in get_extended_env
    ext_env['PATH'] = os.pathsep.join(add_to_PATH + [PATH])
TypeError: Can't convert 'list' object to str implicitly
```

**Comment by goetzc** [comment]
I come here with the same error in Sublime Text. 
Before adding the `add_to_PATH` settings, I got this error:
```
SublimeHaskell: ghc-mod was not found!
It is used for LANGUAGE and import autocompletions and type inference.
Try adjusting the 'add_to_PATH' setting.
```
Which is not so explicit about the string array. Would you like to add a more descriptive message?
