### ISSUE TITLE
Right-click symbol, select Show symbol info

### ISSUE THREAD

**Issue by mrkafk** [SublimeHaskell/SublimeHaskell#199]
ST2, Python 2.7.8:

Sublime Haskell: hsdev returns error: File '/home/mark/haskell/code_learn/hw.hs' not found, details: {}
Sublime Haskell: hsdev returns error: File '/home/mark/haskell/code_learn/hw.hs' not found, details: {}
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./autocomplete.py", line 868, in run
  File "./sublime_haskell_common.py", line 816, in show_status_message
TypeError: unbound method status() must be called with StatusMessage instance as first argument (got str instance instead)

**Comment by mvoidex** [comment]
Reopen issue, if it still doesn't work
