### ISSUE TITLE
hsdev branch build fails

### ISSUE THREAD

**Issue by sumo** [SublimeHaskell/SublimeHaskell#201]
Error is:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "C:\Users\sraja2\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\cabalbuild.py", line 299, in run
    has_tests = len(projects[current_project_name]['description']['tests']) > 0
KeyError: 'description'
```

**Comment by mvoidex** [comment]
Fixed
