### ISSUE TITLE
hsdev: "SublimeHaskell: build" stops working

### ISSUE THREAD

**Issue by doubleloop** [SublimeHaskell/SublimeHaskell#206]
I am using command "SublimeHaskell: build" which works perfectly fine until something goes wrong and I can not use it any more with message:  
```
"SublimeHaskell: No project found, did you add some .cabal file?"
```
in status bar. Everything is back to normal after sublime restart.

Not sure if this is the reason but every time it happens, the last stack trace in console is:
```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 335, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 1908, in on_query_context
    return can_complete_qualified_symbol(get_qualified_symbol(preline))
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 520, in can_complete_qualified_symbol
    return list(filter(lambda m: m.startswith(module_name), autocompletion.get_current_module_completions())) != []
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/hsdev.py", line 64, in wrapped
    return fn(*args, **kwargs)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 492, in get_current_module_completions
    return set([m.name for m in hsdev_client.scope_modules(self.current_filename or current_dir)])
TypeError: 'NoneType' object is not iterable
```

**Comment by doubleloop** [comment]
I pasted wrong stack trace :P 
the proper one is:
```
Traceback (most recent call last):
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/parseoutput.py", line 164, in <lambda>
    sublime.set_timeout(lambda: write_output(view, output, base_dir), 0)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/parseoutput.py", line 318, in write_output
    error_view = output_panel(view.window(), text, panel_name = ERROR_PANEL_NAME, syntax = 'HaskellOutputPanel')
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/sublime_haskell_common.py", line 623, in output_panel
    output_view = window.get_output_panel(panel_name)
AttributeError: 'NoneType' object has no attribute 'get_output_panel'
```

**Comment by mvoidex** [comment]
Must be fixed
