### ISSUE TITLE
hsdev: import qualified

### ISSUE THREAD

**Issue by doubleloop** [SublimeHaskell/SublimeHaskell#210]
```haskell
import qualified Data.Map as M

-- now type M.
```

you get:

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 335, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 1933, in on_query_context
    return can_complete_qualified_symbol(get_qualified_symbol(preline))
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 535, in can_complete_qualified_symbol
    return list(filter(lambda m: m.startswith(info.module), autocompletion.get_current_module_completions())) != []
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/hsdev.py", line 66, in wrapped
    return fn(*args, **kwargs)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 508, in get_current_module_completions
    return set([m.name for m in hsdev_client.scope_modules(self.current_filename or current_dir)])
TypeError: 'NoneType' object is not iterable
```

and if you type `M.<ctrl-space>` you get another:
```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 358, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 1831, in on_query_completions
    completions = autocompletion.get_completions(view, prefix, locations)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/hsdev.py", line 66, in wrapped
    return fn(*args, **kwargs)
  File "/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 402, in get_completions
    if len(ms) > 1:
TypeError: object of type 'NoneType' has no len()
```
and available completions is a list of keywords

**Comment by mvoidex** [comment]
Fixed
