### ISSUE TITLE
Error on ghc-mod invocation

### ISSUE THREAD

**Issue by hcarvalhoalves** [SublimeHaskell/SublimeHaskell#211]
I get this error after saving file:

```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/Users/hcarvalhoalves/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/ghcmod.py", line 231, in wait_ghcmod_and_parse
    stdout = call_ghcmod_and_wait(args, filename)
  File "/Users/hcarvalhoalves/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 574, in call_ghcmod_and_wait
    raise Exception("%s exited with status %d and stderr: %s" % (' '.join(command), exit_code, err))
Exception: ghc-mod check /Users/hcarvalhoalves/Desktop/ParTest.hs -g -i /Users/hcarvalhoalves/Desktop exited with status 1 and stderr: ghc-mod: target ‘-g’ is not a module name or a source file
```

I'm using Sublime Haskell's `hsdev` branch on ST3. `ghc-mod` installed is 5.2.1.2.

**Comment by hcarvalhoalves** [comment]
That really is some strange bug. According to the [README.md](https://github.com/SublimeHaskell/SublimeHaskell/blob/hsdev/README.md) `ghc-mod` shouldn't be used if using `hsdev`, and I have it enabled in my settings:

```
{
	"enable_hdevtools": false,
	"enable_hsdev": true,
    "add_to_PATH": ["/Users/hcarvalhoalves/Library/Haskell/bin"]
}
```

**Comment by mvoidex** [comment]
Yes, `hsdev ghc-mod check` must be called. Thanks for report

**Comment by nh2** [comment]
Regarding the exception itself, this seems to do it for me:

```diff

diff --cc sublime_haskell_common.py
index 13863be,13863be..37d7e46
--- a/sublime_haskell_common.py
+++ b/sublime_haskell_common.py
@@@ -446,7 -446,7 +446,7 @@@ def get_ghc_opts_args(filename = None, 
      opts = get_ghc_opts(filename, add_package_db, cabal)
      args = []
      for opt in opts:
--        args.extend(["-g", opt])
++        args.extend(['--ghcOpt="' + opt + '"'])
      return args
  
  def call_ghcmod_and_wait(arg_list, filename=None, cabal = None):
@@@ -458,7 -458,7 +458,7 @@@
      ghc_opts_args = get_ghc_opts_args(filename, add_package_db = False, cabal = cabal)
  
      try:
--        command = attach_cabal_sandbox(['ghc-mod'] + arg_list + ghc_opts_args, cabal)
++        command = attach_cabal_sandbox(['ghc-mod'] + ghc_opts_args + arg_list, cabal)
  
          # log('running ghc-mod: {0}'.format(command))
  ```

But we have to check whether it is actually correct do to it this way and whether it also works with the old version of ghc-mod (or we just require the newer one, also OK).

**Comment by hcarvalhoalves** [comment]
Applied your patch... wow, everything autocompletes beautifully in this branch! Thanks a lot.
