### ISSUE TITLE
SublimeHaskell/sublime_haskell_common.py?

### ISSUE THREAD

**Issue by mooreniemi** [SublimeHaskell/SublimeHaskell#219]
```Exception in thread Thread-4:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/Alex/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 918, in run
    '-outputdir', CABAL_INSPECTOR_OBJ_DIR])
  File "/Users/Alex/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 135, in call_and_wait
    return call_and_wait_with_input(command, None, **popen_kwargs)
  File "/Users/Alex/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 173, in call_and_wait_with_input
    **popen_kwargs)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'ghc'```

**Comment by mvoidex** [comment]
I have not enough time now, but i'll try to get into as soon as possible

**Comment by cmahon** [comment]
I experienced the same error after launching ST3 from the OS X desktop but it works fine when launching from the command line using subl, presumably because ghc is on the PATH in that case.

**Comment by mvoidex** [comment]
Hi, doesn't adding ghc to 'add_to_PATH' help?

	// Extra directories to be added to the front of the PATH environment variable.
	// Specify this for using custom ghc, cabal, and ghc-mod
	// Example: /home/user/.cabal/bin
	"add_to_PATH": [],

**Comment by mooreniemi** [comment]
@cmahon like chris, i also have no issue if i launch from terminal. i tried `add_to_PATH` but still the same errors (and i am doing `which ghc | pbcopy` so it really should be the path)

**Comment by mooreniemi** [comment]
also, ghc, ghc-mod, hdevtools, are all on my system $PATH

**Comment by mvoidex** [comment]
I'll close it as there were many changes. Reopen, if it still not working
