### ISSUE TITLE
hsdev branch: Build on save breaks when a Haskell SublimeREPL view is open

### ISSUE THREAD

**Issue by tomv564** [SublimeHaskell/SublimeHaskell#231]
Line 84 of cabalbuild.py assumes all open views return a valid string for file_name(). The resulting None in view_files causes an exception on line 85:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/Users/tomv/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/cabalbuild.py", line 298, in run
    projects = get_projects()
File "/Users/tomv/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/cabalbuild.py", line 85, in get_projects
    src_files = list(map(lambda p: os.path.normcase(os.path.normpath(p)), folder_files + view_files))
  File "/Users/tomv/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/cabalbuild.py", line 85, in <lambda>
    src_files = list(map(lambda p: os.path.normcase(os.path.normpath(p)), folder_files + view_files))
  File "./posixpath.py", line 354, in normpath
AttributeError: 'NoneType' object has no attribute 'starts with'
```

A quick fix is to filter where p.file_name() is None:

``` python
view_files = [v.file_name() for v in sublime.active_window().views() if v.file_name() and (is_haskell_source(v) or is_cabal_source(v))]
```

But the proper fix might be updating is_haskell_source(view) and is_cabal_source in sublime_haskell_common.py.

Let me know if you would like pull requests for this branch.

**Comment by mvoidex** [comment]
Thanks!

> But the proper fix might be updating is_haskell_source and is_cabal_source

They are also used to detect REPL views, so I think quick fix is ok here

**Comment by tomv564** [comment]
Sounds good, thanks!
