### ISSUE TITLE
Status bar: Can't infer type, SublimeHaskell: Symbol * not found X

### ISSUE THREAD

**Issue by YLiLarry** [SublimeHaskell/SublimeHaskell#237]
Hello I've been struggling with this problem. 

The auto-build works perfectly, it shows me warnings and error highlight errors whenever I save. Thank you for the awesome work.

However, nothing involving types works at all. I have both ghc-mod and hdevtools installed in my $PATH and I'm able to access them through the command line:
eg. hdevtools type [file] [line] [col]

When I use `shift+cmd+p` to choose `Show type`, the status bar displays `SublimeHaskell: Can't infer type X`, no error message is in the sublime Console

When I choose `Show Symbol Info`, the status bar displays `SublimeHaskell: Symbol * not found X`, again without any error message in the Console.

`ghc-mod` and `hdevtools` are in "/Users/Larry_Li/.local/bin/" which is added to the settings:
	`"add_to_PATH": ["/Users/Larry_Li/.local/bin/","/Users/Larry_Li/.stack/programs/x86_64-osx/ghc-7.10.2/bin/"]`

Any idea what might be the issue?

**Comment by YLiLarry** [comment]
I tested on both ST2/3, they both not work.

my settings:

`{
	// Enables ghc-mod (you should have it installed,
	// e.g. via cabal install ghc-mod).
	// See the add_to_PATH settings to specify a custom location.
	"enable_ghc_mod": true,

	// Enable auto completion of module imports
	"auto_complete_imports": true,

	// Enable auto completion of LANGUAGE pragmas
	"auto_complete_language_pragmas": true,

	// Enable auto build on save
	"enable_auto_build": true,

	// Enable auto run tests on save, has effect only if auto build enabled (enable_auto_build)
	"auto_run_tests": false,

	// Enable auto check on save
	"enable_auto_check": true,

	// Enable auto lint on save (as hints when building)
	"enable_auto_lint": true,

	// How to build the cabal project in order to obtain error messages.
	// This option exists because `cabal build` is slow and cannot re-print
	// warnings of already compiled modules.
	// (Also see https://github.com/haskell/cabal/issues/1179, cabal 1.16).
	//
	// Possible values:
	// - "normal"
	//   Uses a full `cabal build`, generating object files and binaries.
	//   If this takes too long for you, look at the other options.
	// - "normal-then-warnings"
	//   Like "normal", but afterwards also collects project-wide warnings with
	//   `cabal build --ghc-options="-fforce-recomp -Wall -fno-code"`
	//   (this recompiles everything, but skips code generation for speed).
	// - "typecheck"
	//   Performs a type check of the whole project, trying to not do any more
	//   than that in order to give faster feedback (that "normal").
	//   Currently uses `cabal build --ghc-options="-c"` to skip linking.
	// - "typecheck-then-warnings"
	//   Like "typecheck", but afterwards collects warnings like
	//   "normal-then-warnings".
	//
	// Please note that it is currently impossible to properly use a `-fno-code`
	// build on a cabal project that links a shared library; it errors too early.
	// (https://github.com/haskell/cabal/issues/1176, cabal 1.16).
	"auto_build_mode": "typecheck",

	// Show output window on build/check/lint:
	"show_output_window": true,

	// Extra directories to be added to the front of the PATH environment variable.
	// Specify this for using custom ghc, cabal, and ghc-mod
	// Example: /home/user/.cabal/bin
	"add_to_PATH": ["/Users/Larry_Li/.local/bin/","/Users/Larry_Li/.stack/programs/x86_64-osx/ghc-7.10.2/bin/"],

	// Use cabal-dev
	"use_cabal_dev": false,

	// Sandbox for cabal-dev
	"cabal_dev_sandbox": "",

	// Cabal-dev sandboxes
	"cabal_dev_sandbox_list": [],

	// Inhibit default Sublime word completions
	"inhibit_completions": true,

	// Auto autocompletion popup on '.' in import list
	"auto_completion_popup": true,

	// Additional ghc options for use in ghc-mod and ModuleInspector, for example "-package ghc"
	"ghc_opts": [],

	// Enables hdevtools (it must be installed, cabal install hdevtools)
	// See the add_to_PATH settings to specify a custom location.
	"enable_hdevtools": false,

	// hdevtools socket name or default
	"hdevtools_socket": "",

	// Enable hdocs, disabled by default since 'hdocs' is not on hackage yet
	// It can be manually installed from http://github.com/mvoidex/hdocs
	"enable_hdocs": true,

	// Enable inpecting modules with SublimeHaskell's ModuleInspector.
	// Needed for autocompletion.
	// This can take a lot of time in really big Haskell projects.
	// Changing this requires a Sublime restart.
	"inspect_modules": false,

	// Relative or absolute path to a folder where local caches are stored.
	// The same folder is used to store the CabalInspector/ModuleInspector tools.
	// This setting is useful for preventing auto-generated or inherently local
	// files from being synchronized by Dropbox and the like.
	// Changing this requires a Sublime restart.
	// Examples:
	// 		"cache_path": "../../Local/SublimeHaskell"
	// 		"cache_path": "%TEMP%\\SublimeHaskell"
	"cache_path": "."
}`

**Comment by YLiLarry** [comment]
osx 10.10.5
ghc-mod version 5.3.0.0 compiled by GHC 7.10.2

**Comment by YLiLarry** [comment]
When I choose `Type & link` the console displays an error:

````
Exception in thread Thread-659:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./ghcmod.py", line 119, in wait_ghcmod_and_parse
  File "./sublime_haskell_common.py", line 458, in call_ghcmod_and_wait
  File "./sublime_haskell_common.py", line 446, in get_ghc_opts_args
  File "./sublime_haskell_common.py", line 438, in get_ghc_opts
  File "./sublime_haskell_common.py", line 393, in get_source_dir
  File "./sublime_haskell_common.py", line 135, in call_and_wait
  File "./sublime_haskell_common.py", line 173, in call_and_wait_with_input
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
````

**Comment by YLiLarry** [comment]
`stylish-haskell` under the same `bin` directory works when i choose `SublimeHaskell: Stylish`. This confirms that sublimehaskell should be able to reach the binaries

**Comment by YLiLarry** [comment]
I think I found the problem. The ghc-mod does not work with stack. The error is gone if I can successfully build with cabal.
