### ISSUE TITLE
Lint failed

### ISSUE THREAD

**Issue by nineonine** [SublimeHaskell/SublimeHaskell#241]
Exception in thread Thread-59:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/Users/nineonine/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/ghcmod.py", line 243, in wait_ghcmod_and_parse
    stdout = call_ghcmod_and_wait(args, filename)
  File "/Users/nineonine/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 579, in call_ghcmod_and_wait
    raise Exception("%s exited with status %d and stderr: %s" % (' '.join(command), exit_code, err))
Exception: ghc-mod lint -h -u /Users/nineonine/Programming/Haskell/exercism/WordProcessor.hs -g -i /Users/nineonine/Programming/Haskell/exercism exited with status 1 and stderr: Usage for `lint' command:
- lint FILE
  Check files using `hlint'.
  Flags:
    -h
        Option to be passed to hlint.

ghc-mod: Invalid command line form.

**Comment by bscottm** [comment]
Merged commit, closing issue.
