### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by mankyKitty** [SublimeHaskell/SublimeHaskell#263]
Hi there,

I haven't been able to find a similar issue in the list already, so apologies if this is already here. Running ST3 Build 3103, and hsdev 0.1.8.2 and I'm seeing the following errors in the console when SublimeHaskell actions are triggered. Like autocomplete or linting etc... Digging into it when I get a moment, but if anyone has any suggestions, that'd be awesome.
```

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/Users/schalmers/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 1972, in on_query_completions
    completions = autocompletion.get_completions(view, prefix, locations)
  File "/Users/schalmers/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 301, in wrapped
    return fn(*args, **kwargs)
  File "/Users/schalmers/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 421, in get_completions
    current_module = head_of(hsdev_client.module(file = current_file_name))
  File "/Users/schalmers/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 125, in head_of
    if len(l) > 0:
TypeError: object of type 'NoneType' has no len()
Sublime Haskell: listen: connection to hsdev lost: 'str' object has no attribute 'items'
Sublime Haskell: Starting hsdev server
Sublime Haskell: hsdev server started at port 4567
Sublime Haskell: connecting to hsdev server (0)...
Sublime Haskell: connected to hsdev serverSublime Haskell: connecting to hsdev server (0)...

Sublime Haskell: connected to hsdev server
Sublime Haskell: listen: connection to hsdev lost: 'str' object has no attribute 'items'
Sublime Haskell: Starting hsdev server
Sublime Haskell: hsdev server started at port 4567
Sublime Haskell: connecting to hsdev server (0)...Sublime Haskell: connecting to hsdev server (0)...

Sublime Haskell: connected to hsdev server
Sublime Haskell: connected to hsdev server
```

**Comment by mvoidex** [comment]
Hi, I'll try to on investigate at weekend

**Comment by mvoidex** [comment]
Not sure about `TypeError: object of type 'NoneType' has no len()`, but `listen: connection to hsdev lost: 'str' object has no attribute 'items'` must be fixed now.
Reopen if there are still some issues
