### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by cmahon** [SublimeHaskell/SublimeHaskell#264]
I get this error for import completions (hsdev 0.1.8.2).

Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/Users/Chris/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 1959, in on_query_completions
    completions = (autocompletion.get_import_completions(view, prefix, locations) +
  File "/Users/Chris/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 301, in wrapped
    return fn(_args, *_kwargs)
  File "/Users/Chris/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 493, in get_import_completions
    import_completions = self.get_module_completions_for(pref)
  File "/Users/Chris/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 301, in wrapped
    return fn(_args, *_kwargs)
  File "/Users/Chris/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 538, in get_module_completions_for
    module_list = modules if modules else self.get_current_module_completions(current_dir = current_dir)
  File "/Users/Chris/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 301, in wrapped
    return fn(_args, *_kwargs)
  File "/Users/Chris/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 551, in get_current_module_completions
    return set([m.name for m in hsdev_client.scope_modules(self.current_filename)])
TypeError: 'NoneType' object is not iterable
Sublime Haskell: hsdev scope modules returns error: tool not found, tool: stack, id: 270

**Comment by bscottm** [comment]
@cmahon: Recently fixed.
