### ISSUE TITLE
FileNotFoundError for wrong path

### ISSUE THREAD

**Issue by crockeea** [SublimeHaskell/SublimeHaskell#268]
When I save a file, I see the following in the log:

```
Sublime Haskell: ghc-mod check didn't exit with success on '/home/eric/Desktop/Lol/lol/tests/TensorTests.hs'
Sublime Haskell: ghc-mod lint -h -u didn't exit with success on '/home/eric/Desktop/Lol/lol/tests/TensorTests.hs'
Traceback (most recent call last):
  File "/home/eric/.config/sublime-text-3/Packages/SublimeHaskell/ghcmod.py", line 256, in <lambda>
    sublime.set_timeout(lambda: mark_messages_in_views(concated_messages), 0)
  File "/home/eric/.config/sublime-text-3/Packages/SublimeHaskell/parseoutput.py", line 248, in mark_messages_in_views
    errors))
  File "/home/eric/.config/sublime-text-3/Packages/SublimeHaskell/parseoutput.py", line 247, in <lambda>
    lambda x: os.path.samefile(view_filename, x.filename),
  File "./python3.3/posixpath.py", line 185, in samefile
FileNotFoundError: [Errno 2] No such file or directory: '/home/eric/Desktop/Lol/lol/tests/tests/TensorTests.hs'
```

Note on that last line, the path includes `test/tests/`, while it should just be `tests/`, like the first two commands. This is likely why the file can't be found.

This report might not be much to go on, but I can provide more info if you tell me how since this happens every time I save the file.

**Comment by bscottm** [comment]
@crockeea: I'm sure you've been waiting very patiently for this to get fixed for the `ghc-mod` backend. I'm confident that this is fixed in the current 2.0.x release. Feel free to re-open.
