### ISSUE TITLE
I have a working ghc-mod, but SH doesn't work it out

### ISSUE THREAD

**Issue by metaleap** [SublimeHaskell/SublimeHaskell#293]
It's on my `%PATH%` and also in `"add_to_PATH": ["C:\\Users\\roxor\\AppData\\Roaming\\local\\bin"]` but when changing a .hs file, then in the Console I see:

    Sublime Haskell: ghc-mod check didn't exit with success on 'D:\dev\hs\hax2\Tmpl.hs'
    Sublime Haskell: ghc-mod lint -h -u didn't exit with success on 'D:\dev\hs\hax2\Tmpl.hs'
    Exception in thread Thread-11:
    Traceback (most recent call last):
      File "./python3.3/threading.py", line 901, in _bootstrap_inner
      File "./python3.3/threading.py", line 858, in run
      File "C:\Users\roxor\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\check_lint.py", line 258, in wait_ghcmod_and_parse
        alter_messages_cb(parsed_messages)
      File "C:\Users\roxor\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\check_lint.py", line 210, in show_current_file_first_and_alter
        msgs.sort(key=sort_key)
      File "C:\Users\roxor\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\check_lint.py", line 206, in sort_key
        a[1].start.line,
    AttributeError: 'OutputMessage' object has no attribute 'start'

Now from a command-prompt I can easily `ghc-mod lint -h -u D:\dev\hs\hax2\Tmpl.hs` just fine and it puts out all kinds of suggestions, same for `ghc-mod check`; so I suppose it's the threading exception that's the issue here. ST3 build 3126

**Comment by metaleap** [comment]
Must have been an initial/incomplete-setup issue at my end, as I haven't encountered the above anymore since then. (As I'm not using "properly defined projects" (stack/cabal yamls with deps etc), neither the hsdev nor the ghc-mod seem to yield usable outputs, but that's my own fault and no big deal.)
