### ISSUE TITLE
Doesn't work on OSX El Capitan

### ISSUE THREAD

**Issue by paxter** [SublimeHaskell/SublimeHaskell#375]
I've got that log message:
`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/Users/empire/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/zzplugin.py", line 34, in plugin_loaded
    backend_mgr.get_backends()
  File "/Users/empire/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/internals/backend_mgr.py", line 140, in get_backends
    self.possible_backends = self.filter_possible(Settings.PLUGIN.backends)
  File "/Users/empire/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/internals/backend_mgr.py", line 208, in filter_possible
    if ubclazz is not None and ubclazz.is_available(**ubackend.get('options', {})):
  File "/Users/empire/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 93, in is_available
    hsdev_ver = HsDevBackend.hsdev_version(kwargs.get('exec-with'), kwargs.get('install-dir'))
  File "/Users/empire/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 212, in hsdev_version
    hsdev_proc = ProcHelper.exec_with_wrapper(exec_with, install_dir, ['hsdev', 'version'])
  File "/Users/empire/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/internals/proc_helper.py", line 175, in exec_with_wrapper
    raise RuntimeError('ProcHelper.exec_with_wrapper: invalid install_dir (None)')
RuntimeError: ProcHelper.exec_with_wrapper: invalid install_dir (None)
environment variables loaded using: /bin/bash -l`

Tried to change the "add_to_PATH", but doesn't work.
`add_to_PATH": ["~/Library/Haskell/bin" ]`

Also the menu entry is broken:
https://i.imgur.com/ZYnLerk.png

I'm using hsdev version 0.2.5.1 and installed sublimeHaskell through the Package Control.

**Comment by bscottm** [comment]
@paxter: You don't have all of the options (`install_dir`, specifically) set for a `stack` or `cabal`-wrapped `hsdev` backend. Which are you trying to use?

**Comment by paxter** [comment]
I tried to use the default backend:

`        "Local hsdev": {
            "default": true,
            "backend": "hsdev",
            "options": {
              "local": true,
              "port": 4567
            }
        }`

**Comment by bscottm** [comment]
@paxter: Ok, it's a bug I need to take a look at. Thanks for reporting it and finding a workaround while I investigate.
