### ISSUE TITLE
Random error in console

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#389]
I have a lot of instances of this error in the console:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 479, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "/home/ser/.config/sublime-text-3/Packages/SublimeHaskell/zzplugin.py", line 171, in on_post_save
    successful_build = EventCommon.do_check_lint(view)
  File "/home/ser/.config/sublime-text-3/Packages/SublimeHaskell/event_common.py", line 32, in do_check_lint
    return CheckAndLint.exec_check_and_lint(view)
  File "/home/ser/.config/sublime-text-3/Packages/SublimeHaskell/check_lint.py", line 121, in exec_check_and_lint
    successful = chain_runner.run_chain([hsdev_check(), hsdev_lint()], 'Checking and Linting', fly_mode=fly_mode)
  File "/home/ser/.config/sublime-text-3/Packages/SublimeHaskell/check_lint.py", line 61, in run_chain
    _, retval = self.go_chain(cmds)
  File "/home/ser/.config/sublime-text-3/Packages/SublimeHaskell/check_lint.py", line 81, in go_chain
    resp, status = retval
ValueError: need more than 0 values to unpack
```

Not sure how to trigger it though.

SublimeHaskell 2.1.16, Sublime Text 3156, fully updated Manjaro Linux.

**Comment by bscottm** [comment]
@Pastafarianist: Which backend are you using?

**Comment by Pastafarianist** [comment]
Still `none`. See my config [here](https://github.com/SublimeHaskell/SublimeHaskell/issues/388#issue-287422584).

**Comment by Pastafarianist** [comment]
https://github.com/SublimeHaskell/SublimeHaskell/issues/388#issuecomment-357075817
