### ISSUE TITLE
Traceback when manually Checking and Linting

### ISSUE THREAD

**Issue by ROpdebee** [SublimeHaskell/SublimeHaskell#401]
Running `SublimeHaskell: Check & Lint` leads to a Traceback:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/ruben/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/check_lint.py", line 151, in run
    exec_check_and_lint(self.view, fly_mode=kwargs.get('fly', False))
  File "/Users/ruben/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/check_lint.py", line 136, in exec_check_and_lint
    chain_runner.run_chain([hsdev_check(), hsdev_lint()], fly_mode=fly_mode)
  File "/Users/ruben/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/check_lint.py", line 55, in run_chain
    ParseOutput.hide_output(self.view)
AttributeError: 'module' object has no attribute 'hide_output'
```

Seems like a result of https://github.com/SublimeHaskell/SublimeHaskell/commit/18e3d1c28daf96eff8350b7d64568ef5e73dd17d

**Comment by bscottm** [comment]
@ROpdebee: Will release a fix tomorrow (Monday, 5 FEB [PST], my timezone.)

**Comment by bscottm** [comment]
@ROpdebee: Good to close this?

**Comment by ROpdebee** [comment]
Yes.
