### ISSUE TITLE
Icons are broken with the Cubicle color scheme

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#408]
![capture](https://user-images.githubusercontent.com/287532/36159365-333e3888-10e7-11e8-89f3-e98880c548ad.PNG)

**Comment by bscottm** [comment]
@moodmosaic: Not sure what to tell you on this one. What ST3 build are you on? If it's 3157, there's all kinds of breakage happening... But I'll look into it when I have a chance.

**Comment by moodmosaic** [comment]
I'm on the latest stable one, build 3143.

**Comment by bscottm** [comment]
Ugh. Sounds like a theme issue. Will diagnose in the near future -- hopefully this isn't mission critical. :-)

**Comment by moodmosaic** [comment]
Anything I can do to help? Where should I look at? Happy to help :-)

**Comment by bscottm** [comment]
@moodmosaic: Off the top of my head, no, I don't have a clear idea where to start looking. It's probably in the theme itself.

**Comment by bscottm** [comment]
@moodmosaic: Cubicle doesn't come up under PackageControl: Install Package. Where do I get it?

**Comment by moodmosaic** [comment]
It comes with SublimeHaskell: https://github.com/SublimeHaskell/SublimeHaskell/blob/master/Themes/Cubicle.tmTheme

**Comment by bscottm** [comment]
@moodmosaic: Doh!

**Comment by moodmosaic** [comment]
But the icons looks crappy.

**Comment by moodmosaic** [comment]
I love the Cubicle theme, I just wish that the icons show up correctly.

**Comment by bscottm** [comment]
@moodmosaic: Just scanning through the code... it might have to do with the "gutter theme". I'm looking into it...

**Comment by moodmosaic** [comment]
These? http://www.sublimelinter.com/en/latest/gutter_themes.html

(I thought we were just using the icons in the `Icons` folder...)

**Comment by bscottm** [comment]
@moodmosaic: What Theme (not color scheme) are you using?

**Comment by moodmosaic** [comment]
The adaptive one from Sublime (it comes with 2 built- in themes; it happens with both of them).

**Comment by bscottm** [comment]
@moodmosaic: There were missing scope names in the color theme. Took a while to figure that out. Apologies for the delay. 2.1.26 pushes the updated theme.

**Comment by moodmosaic** [comment]
Wow, awesome, I'll try it tomorrow. I'm on the hsdev-3 branch, I'll see if I can apply the fix on this branch locally :-)

**Comment by bscottm** [comment]
@moodmosaic: You will probably have to reapply the color scheme to get it to work. ST3 doesn't seem to pick up the change automagically.

**Comment by bscottm** [comment]
@moodmosaic: Just do a `git pull`. I merged the fixes from `master` for you. And discovered the underlying reason why `on_post_save` gets invoked twice (not sure if you or @mvoidex put that update time hack into the code.)

Let me know if the console has messages about duplicate saves.

**Comment by moodmosaic** [comment]
Icons are back working again for Cubicle 🎉 But it looks like something is broken now and hdocs aren't working at all in hsdev-3 branch:

```
...
reloading plugin SublimeHaskell.types
reloading plugin SublimeHaskell.zzplugin
plugins loaded
plugin 'backends' ['Cabal-sandboxed local hsdev', 'Local hsdev', 'Cabal new-build local hsdev', 'No backend', 'ghc-mod', 'Stack-exec local hsdev', 'Remote hsdev@localhost:4567']
Possible/usable 'backends': ['Remote hsdev@localhost:4567', 'Cabal new-build local hsdev', 'Local hsdev', 'No backend']
Traceback (most recent call last):
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 167, in on_load
    self.do_load(view)
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 199, in do_load
    if (Settings.PLUGIN.use_improved_syntax and (name.endswith(".hs") or name.endswith(".hsc"))) or \
NameError: global name 'name' is not defined
<hsdev stderr> [96m2018-02-22 12:08:29 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal/task/package-db-stack[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:08:29 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal/task[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:08:29 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:08:29 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate[m[m> [m[mtool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db[m[m
font face "Times" could not be found, defaulting to "Consolas"
```

However, if I revert https://github.com/SublimeHaskell/SublimeHaskell/commit/54259e5502cc10627653a517c7a32e957781472e then it works.

**Comment by moodmosaic** [comment]
>Icons are back working again for Cubicle. But it looks like something is broken now and hdocs aren't working at all in hsdev-3 branch:

However, if I revert https://github.com/SublimeHaskell/SublimeHaskell/commit/54259e5502cc10627653a517c7a32e957781472e then it works.

**Comment by moodmosaic** [comment]
>Let me know if the console has messages about duplicate saves.

It seems to work a whole lot faster now, (though I had to revert https://github.com/SublimeHaskell/SublimeHaskell/commit/54259e5502cc10627653a517c7a32e957781472e), and everything works fine in general.

I *do* see a whole bunch of errors in the console though:

```
reloading plugin SublimeHaskell.zzplugin
plugins loaded
plugin 'backends' ['Cabal new-build local hsdev', 'No backend', 'Remote hsdev@localhost:4567', 'Stack-exec local hsdev', 'Cabal-sandboxed local hsdev', 'ghc-mod', 'Local hsdev']
Possible/usable 'backends': ['Cabal new-build local hsdev', 'Local hsdev', 'No backend', 'Remote hsdev@localhost:4567']
Quick panel unavailable
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 167, in on_load
    self.do_load(view)
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 199, in do_load
    if (Settings.PLUGIN.use_improved_syntax and (name.endswith(".hs") or name.endswith(".hsc"))) or \
NameError: global name 'name' is not defined
<hsdev stderr> [96m2018-02-22 12:21:45 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal/task/package-db-stack[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:21:45 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal/task[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:21:45 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:21:45 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate[m[m> [m[mtool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db[m[m
font face "Times" could not be found, defaulting to "Consolas"
Assigning hs to syntax Packages/SublimeHaskell/Syntaxes/Haskell-SublimeHaskell.sublime-syntax
reloading settings Packages/User/Haskell-SublimeHaskell.sublime-settings
Traceback (most recent call last):
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 167, in on_load
    self.do_load(view)
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 199, in do_load
    if (Settings.PLUGIN.use_improved_syntax and (name.endswith(".hs") or name.endswith(".hsc"))) or \
NameError: global name 'name' is not defined
Traceback (most recent call last):
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 167, in on_load
    self.do_load(view)
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 199, in do_load
    if (Settings.PLUGIN.use_improved_syntax and (name.endswith(".hs") or name.endswith(".hsc"))) or \
NameError: global name 'name' is not defined
<hsdev stderr> [96m2018-02-22 12:27:30 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mghc/cache-warnings/types[m[m> [m[mScope leaves with exception: Variable not in scope:
<hsdev stderr>   sprint :: Either ErrorMessage [MarketSummary] -> IO a0
<hsdev stderr> 
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:27:30 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mghc/cache-warnings[m[m> [m[mScope leaves with exception: Variable not in scope:
<hsdev stderr>   sprint :: Either ErrorMessage [MarketSummary] -> IO a0
<hsdev stderr> 
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:27:30 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/task/types[m[m> [m[mScope leaves with exception: ghc exception: Variable not in scope:
<hsdev stderr>   sprint :: Either ErrorMessage [MarketSummary] -> IO a0
<hsdev stderr> 
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:27:30 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/task[m[m> [m[mScope leaves with exception: ghc exception: Variable not in scope:
<hsdev stderr>   sprint :: Either ErrorMessage [MarketSummary] -> IO a0
<hsdev stderr> 
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
indexing [job 12]: no files were indexed out of the 4 queued, abandoning crawl
```
