### ISSUE TITLE
enabling autocomplete

### ISSUE THREAD

**Issue by rainwolf** [SublimeHaskell/SublimeHaskell#416]
I can't get autocomplete to work at all, at most it suggests words that are already in the file or some of the few snippets, but never those fancy ones I see in the gifs, the ones that come with function definitions, or suggestions from imports of base packages.
I'm on a mac, with the latest ST and SublimeHaskell, installed my Haskell platform with stack. hsdev seems to work. Any suggestion on where to look will be highly appreciated.

Additionally, I get to see the icons on the left hand side, but not specific SublimeHaskell popovers. Auto Fix gets stuck in a read-only mode and the key-bindings for auto-fix don't work for me. 

Does the variable "name" on line 191 of zzplugin.py need to be replaced with "filename"?

**Comment by bscottm** [comment]
@rainwolf: Looking into it.

**Comment by bscottm** [comment]
@rainwolf: Found the problem. My bad. Should show up on Package Control as 2.1.28.

**Comment by rainwolf** [comment]
I tried it, but now it's spitting the error `AttributeError: 'SublimeHaskellEventListener' object has no attribute 'do_completions'`

For the popover I am getting (for both the icons and in the code)

> Sublime Haskell: worker: job SublimeHaskellPopup.on_hover failed, see console window traceback
Traceback (most recent call last):
  File "/Users/waliedothman/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/internals/utils.py", line 63, in worker_run
    worker_fn(*args, **kwargs)
  File "/Users/waliedothman/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/info_popup.py", line 148, in do_hover
    popup_parts = [self.STYLES.gen_style(self.view.settings().get('color_scheme'))]
  File "/Users/waliedothman/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/info_popup.py", line 76, in gen_style
    scheme = self.load_scheme(scheme_path)
  File "/Users/waliedothman/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/info_popup.py", line 53, in load_scheme
    self.schemes[scheme_path] = self.collect_scheme(ElementTree.fromstring(scheme_res))
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by bscottm** [comment]
@rainwolf: 2.1.29 has that fix in it.

**Comment by bscottm** [comment]
@rainwolf: 2.1.30 pushed to resolve issue 417. Let me know if the `info_popup` traceback still occurs. I wasn't able to reproduce with ST3 Build 3143 or 3156.

**Comment by rainwolf** [comment]
I'm on ST3 3157, and SH 2.1.30, I get the same traceback for the popovers and no code completion (except the built-in one from ST). Perhaps something else is the culprit but I have no idea what it could be.

**Comment by rainwolf** [comment]
Progress: the popups do work now, and the reason was that they _only_ work with the Hasky color scheme. 

Fancy autocomplete still doesn't work. One error that keeps coming back and doesn't repeat is 

> <hsdev stderr> 2018-03-16 17:05:31 +0100	ERROR	:127.0.0.1:51777/update> cache writing exception: /Users/xxxxxxx/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/standalone.json: openBinaryFile: resource busy (file is locked)

The JSON file does seem to contain relevant info for completion suggestions.

**Comment by bscottm** [comment]
@rainwolf: That's interesting, re: other colou?r schemes. The "file is locked" is actually innocuous, happens due to an issue in `hsdev` itself (conflicting threads, IIRC).

**Comment by rainwolf** [comment]
Then I'm a bit lost. Even when I set the log level to 5 (Trace), there are no errors. Hsdev does return completions when I use it on the commandline, but I never get any other autocomplete popup than the built-in ST one, just single words, no context like function signatures.

**Comment by rainwolf** [comment]
sigh, going back to ST 3143 fixed everything. Even the popups now work with alternate color schemes. I should have tried that sooner, my sincere apologies for wasting your time with this.

**Comment by bscottm** [comment]
@rainwolf: That's interesting, re: other colou?r schemes. The "file is locked" is actually innocuous, happens due to an issue in `hsdev` itself (conflicting threads, IIRC).

**Comment by bscottm** [comment]
@rainwolf: Here's the problem: ST3 > 3143 changed the format of the color schemes. Took me a while to figure out that the default color schemes shipped with ST3 (3157) were converted. They're no longer XML-ish, but JSON. I can identify the converted color schemes by their file extension (`sublime-color-scheme`) and adapt.

Thanks for the crucial clue: ST3 3157 vs. ST3 3143. That helped a lot!

**Comment by rainwolf** [comment]
Good to hear it wasn't completely useless.

While the fancy completions work, I don't get any completions for module imports of any of the base packages like Data.Tuple. I am fairly sure the ghc I use is the same that was used to compile hsdev.
(Stack uses a sandboxed ghc I believe and wouldn't compile hsdev because of conflicting dependencies, I then installed a system-wide ghc and used cabal to compile hsdev).

Any pointers to resolve this?

**Comment by bscottm** [comment]
@rainwolf: Usually it is the result of a GHC `hsdev`/project mismatch. Which version is installed system-wide? And which version was supposed to be installed via `stack`?

**Comment by bscottm** [comment]
If you're using `stack` for your project, try this:

    stack exec hoogle generate

Let me know how that works out. Now, back to answering why peace doesn't automagically ensue when von Clausewitz states that it should when the cost of effort exceeds the political objective...

**Comment by rainwolf** [comment]
To clarify, I'm trying to get completions from module imports (of mostly base packages) in single haskell files, not haskell files in a project. Is that possible?

For my latest experiments to get things to work, I no longer have a system-wide GHC, the IntelliJ Haskell plugin seems to always install 8.2.2, but to get hsdev-0.2.5.1 compiled with stack it downloaded 8.0.2. 
But no luck in getting import completions.

I'll have to give the stack manual a thorough read first before I mess around with a haskell project.

**Comment by bscottm** [comment]
@rainwolf: You can `hoogle generate` without `stack`, if `hoogle` is installed. Will look into the `Data.Tuple` module completions. For some reason, I thought you were having documentation issues.

**Comment by rainwolf** [comment]
for the purpose of not wasting your time, I wanted to let you know I won't dig into this issue further as I found a plugin that seems to satisfy my needs. 
A serious thank you for all the effort you put into support and development of this plugin.

**Comment by bscottm** [comment]
@rainwolf: Can I ask which one?

**Comment by rainwolf** [comment]
Absolutely. It's [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine)

**Comment by bscottm** [comment]
@rainwolf: That's probably the vision of the future Haskell support. It sounds like it has matured significantly since last summer. I'll have to check it out.
