### ISSUE TITLE
Keep getting reading cache: IO expection / Popup resource not found

### ISSUE THREAD

**Issue by JimmyTinsley** [SublimeHaskell/SublimeHaskell#424]
I got error message from Sublime Text 3 console like this 

<hsdev stderr> 2018-05-21 11:40:26.211 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.tools.makedeb.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:26.830 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.stack.snapshots.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:35.261 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.tools.apisimulations.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:36.318 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.tools.bonanza.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:37.427 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.typescommonjournal.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:38.521 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.tastycannon.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:39.578 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.zauth.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:40.575 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.cassandrautil.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:42.284 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.brigtypes.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:43.187 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.ropes.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:44.092 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.metricscollectd.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:45.000 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.cargoholdtypes.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:45.934 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.waiutilities.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:46.843 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.typescommon.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:48.126 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.metricswai.stackwork.install.x8664osx.lts103.821.pkgdb.json
<hsdev stderr> 2018-05-21 11:40:49.063 +0800	ERROR	:127.0.0.1:54862/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from /Users/liujie/Library/Application Support/Sublime Text 3/Cache/SublimeHaskell/hsdev/cabal/.Users.liujie.Downloads.wireserver.libs.httpclientopensslext.stackwork.install.x8664osx.lts103.821.pkgdb.json

All other functions seem to work well except popup(functions types, warnings). When I try I got error message like this:

Sublime Haskell: worker: job SublimeHaskellPopup.on_hover failed, see console window traceback
Traceback (most recent call last):
  File "/Users/liujie/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/internals/utils.py", line 63, in worker_run
    worker_fn(*args, **kwargs)
  File "/Users/liujie/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/info_popup.py", line 157, in do_hover
    self.create_symbol_popup(typed_expr, decl, suggest_import)
  File "/Users/liujie/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/info_popup.py", line 184, in create_symbol_popup
    popup_parts = [self.STYLES.gen_style(self.view.settings().get('color_scheme'))]
  File "/Users/liujie/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/info_popup.py", line 89, in gen_style
    scheme = self.load_scheme(scheme_path)
  File "/Users/liujie/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/info_popup.py", line 51, in load_scheme
    scheme_res = sublime.load_resource(scheme_path)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found

I am wondering whether it is related to the reading IO expection. By the way, the "show symbol info" function works perfectly while the popup doesn't work, kinda strange.

My ghc version is `8.2.1`, cabal version is `2.0.0.0`, stack version is `1.7.1`, hsdev version is `0.2.5.1`, Sublime Text 3 version is `dev build 3175` and I'm using the newest version of SublimeHaskell

**Comment by Vlix** [comment]
I also get this. My setup is as follows:

* `GHC   8.4.3`
* `Cabal 1.24.0.2`
* `Stack 1.9.3`
* `hsdev 0.2.5.1`
* Sublime Text 3.1.1: `Build 3176`
